// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOayIeu3Lc5ifJ7MQmJEbRTfb8oKE8_o0',
    appId: '1:813407331372:web:571b3ee4b5c7594be21d89',
    messagingSenderId: '813407331372',
    projectId: 'location-78e04',
    authDomain: 'location-78e04.firebaseapp.com',
    storageBucket: 'location-78e04.firebasestorage.app',
    measurementId: 'G-LXEZ07MMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmIrSShEeEFb5lID3W0OYM-CTddD1BqE',
    appId: '1:813407331372:android:47f68cb736686e15e21d89',
    messagingSenderId: '813407331372',
    projectId: 'location-78e04',
    storageBucket: 'location-78e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrt_LUbkoorqPnvYwO065Wl4FiV4oTAtc',
    appId: '1:813407331372:ios:6e4ae5023d77f272e21d89',
    messagingSenderId: '813407331372',
    projectId: 'location-78e04',
    storageBucket: 'location-78e04.firebasestorage.app',
    iosBundleId: 'com.example.location',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrt_LUbkoorqPnvYwO065Wl4FiV4oTAtc',
    appId: '1:813407331372:ios:6e4ae5023d77f272e21d89',
    messagingSenderId: '813407331372',
    projectId: 'location-78e04',
    storageBucket: 'location-78e04.firebasestorage.app',
    iosBundleId: 'com.example.location',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOayIeu3Lc5ifJ7MQmJEbRTfb8oKE8_o0',
    appId: '1:813407331372:web:7082650ab201a6fae21d89',
    messagingSenderId: '813407331372',
    projectId: 'location-78e04',
    authDomain: 'location-78e04.firebaseapp.com',
    storageBucket: 'location-78e04.firebasestorage.app',
    measurementId: 'G-LL9RRRB7EN',
  );
}
